baseURL = "https://jaritaes99.github.io/website/"
title = "Jose Arita-Escalante"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Jose Arita-Escalante"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Jose Arita-Escalante's personal website"
keywords = "research,resumé,personal"
info = ["Research Assistant at NASA GSFC", "Aspiring Theoretical Physicist"]
avatarURL = "images/portrait.jpeg"
#gravatar = "escalantejra@vcu.edu"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/jaritaes99/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/jose-arita-escalante-17526616b"

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Research"
weight = 2
url = "research/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.es]
languageName = ":es:"
title = "José Arita Escalante"

[languages.es.params]
author = "José Arita Escalante"
info = ["Asistente de Investigación en NASA GSFC", "Futuro Físico Teórico"]
description = "Sitio personal de José Arita Escalante"
keywords = "blog,desarrollador,personal"

[[languages.es.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.es.menu.main]]
name = "Investigación"
weight = 2
url = "projects/"

[[languages.es.menu.main]]
name = "Contacto"
weight = 5
url = "contact/"
